apiVersion: v1
kind: Namespace
metadata:
  name: guestbook

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  namespace: guestbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: ui
        image: nginxdemos/hello
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
  namespace: guestbook
spec:
  selector:
    app: guestbook
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
